name: Continuous Testing

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: sudo apt-get install xvfb
      - run: npm install
      - run: npx playwright install
      - run: xvfb-run --auto-servernum -- npm test
        env:
          CI: true
