name: Continuous Testing

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
        with:
          node-version: latest
#      - run: sudo apt-get install xvfb
#      - run: npm install
#      - run: npx playwright install
#      - run: xvfb-run --auto-servernum -- npm test
        env:
          CI: true
