name: Continuous Testing

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install XVFB
      run: sudo apt-get install -y xvfb
    - name: Install Dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run Tests with XVFB
      run: xvfb-run --auto-servernum -- npm test
      env:
        CI: true
